export const state = {
  history: [],
  maxHistory: 200,
  config: null,
  voice: {
    status: null,
    backends: [],
    models: [],
  },
  voiceTraining: {
    overview: null,
    detail: null,
    selectedCharacterId: '',
  },
  astrbot: {
    snapshot: null,
  },
  connected: false,
  sseConnected: false,
  statsHistory: [],
  analyzerLogs: [],
  azLevelChart: null,
  azFreqChart: null,
  selfLearning: {
    groupId: '',
    groups: [],
    overview: null,
    strategy: null,
    styles: [],
    slang: [],
    social: [],
    affection: [],
    goals: [],
    memories: [],
    reviews: [],
    mood: null,
    advancedSummary: null,
    clusters: [],
    scenes: [],
    memoryGraph: { nodes: [], edges: [] },
    runs: [],
    importMode: 'merge',
  },
};

export const runtime = {
  tpChart: null,
  donutChart: null,
  cumulChart: null,
  memChart: null,
  apiCallsChart: null,
  es: null,
  logFilterCurrent: 'all',
};
