import type { VoiceModelEntry } from './types';

export const BUILTIN_VOICE_PRESETS: VoiceModelEntry[] = [
  {
    id: 'preset-dongxuelian',
    name: '冬雪莲',
    character: '冬雪莲',
    backend: 'gpt-sovits',
    recommendedBackend: 'gpt-sovits',
    alternateBackends: ['rvc-compat', 'edge-tts'],
    qualityTier: 'stable',
    trainingStatus: 'reference-only',
    previewHint: '先使用较长的完整句试听，避免过短文本影响清晰度。',
    tags: ['虚拟偶像', '中文', '甜妹', '社区模型'],
    sampleText: '今天也要元气满满地和大家打招呼哦。',
    notes: '预设项已内置，需自行放入对应 GPT-SoVITS 模型文件或配置上游服务。',
    installed: false,
    enabled: true,
    source: 'builtin',
  },
  {
    id: 'preset-yongchutafi',
    name: '永雏塔菲',
    character: '永雏塔菲',
    backend: 'gpt-sovits',
    recommendedBackend: 'gpt-sovits',
    alternateBackends: ['rvc-compat', 'edge-tts'],
    qualityTier: 'stable',
    trainingStatus: 'reference-only',
    previewHint: '默认更适合日常聊天句和中短句播报。',
    tags: ['虚拟偶像', '中文', '直播感', '社区模型'],
    sampleText: '塔菲今天也会认真营业，陪你把这段话念得更像真人。',
    notes: '预设项已内置，需自行放入对应 GPT-SoVITS 模型文件或配置上游服务。',
    installed: false,
    enabled: true,
    source: 'builtin',
  },
  {
    id: 'preset-zh-xiaoxiao',
    name: '晓晓',
    character: '微软晓晓',
    backend: 'edge-tts',
    recommendedBackend: 'edge-tts',
    qualityTier: 'fallback',
    trainingStatus: 'builtin-ready',
    tags: ['系统音色', '中文', '自然'],
    sampleText: '这是内置的自然中文试听音色，可作为模型未就绪时的保底播报。',
    notes: '无需模型文件，可直接作为预览和故障回退音色。',
    installed: true,
    enabled: true,
    source: 'builtin',
  },
  {
    id: 'preset-zh-xiaoyi',
    name: '晓伊',
    character: '微软晓伊',
    backend: 'edge-tts',
    recommendedBackend: 'edge-tts',
    qualityTier: 'fallback',
    trainingStatus: 'builtin-ready',
    tags: ['系统音色', '中文', '女声'],
    sampleText: '如果角色模型暂时没准备好，可以先用我进行更自然的中文播报。',
    notes: '无需模型文件，可直接作为预览和故障回退音色。',
    installed: true,
    enabled: true,
    source: 'builtin',
  },
];
